from turtle import color
import pygame
"""CONFIGURATION MONDE"""

CASE = 20
COL = 38
LIGNE = 35
MARG = 1

LARGEUR_GRILLE = COL*CASE
HAUTEUR_GRILLE = LIGNE*CASE

LARGEUR_MENU = round(COL*2/3)*CASE
HAUTEUR_MENU = HAUTEUR_GRILLE


LARGEUR_ECRAN = LARGEUR_MENU+LARGEUR_GRILLE+2*MARG
HAUTEUR_ECRAN = HAUTEUR_GRILLE+2*MARG

COULEURS = {"fond": (115,64,69), "menu": (49,32,40),"bordure": (160,82,69)}